config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end

  # get 'home/index'
  get '/about', to: 'home#about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_theme

  def set_theme
    if params[:theme].present?
      theme = params[:theme].to_sym
      # session[:theme] = theme
      cookies[:theme] = theme
      redirect_to(request.referer || root_path)
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about
    render 'about'
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, class: "contents") do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>" >
  <p class="my-5">
  <strong class="block font-medium mb-1">Name:</strong>
    <%= friend.first_name %>
    <%= friend.last_name %>
  </p>


  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= friend.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= friend.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Twitter:</strong>
    <%= friend.twitter %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this friend", friend, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this friend', edit_friend_path(friend), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</tr>

app/views/friends/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing friend</h1>

  <%= render "form", friend: @friend %>

  <%= link_to "Show this friend", @friend, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to friends", friends_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/friends/index.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl">Friends</h1>
  <%= link_to 'New friend', new_friend_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>

<div class="overflow-x-auto mt-8">
  <table class="table table-zebra w-full">
    <!-- head -->
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Telephone</th>
        <th>Twitter</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <!-- row 1 -->
      <%# <%= render @friends %>

      <% @friends.each do |friend| %>
        <tr>
          <th><%= friend.id %></th>
          <td><b><%= friend.first_name %> <%= friend.last_name %></b></td>
          <td><%= friend.phone %></td> 
          <td><%= friend.twitter %></td> 
          <td class="flex">
            <%= link_to edit_friend_path(friend), class: "btn mr-2 ml-auto" do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
              </svg>
              <span class="ml-2">edit</span>
            <% end %>
              <%= button_to 'delete', friend_path(friend), method: :delete, class: "btn-error rounded-lg py-3 px-5 font-medium" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/friends/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New friend</h1>

  <%= render "form", friend: @friend %>

  <%= link_to 'Back to friends', friends_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/friends/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @friend %>

    <%= link_to 'Edit this friend', edit_friend_path(@friend), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this friend', friend_path(@friend), method: :delete, class: "btn-error mt-2 rounded-lg py-3 px-5 font-medium" %>
    </div>
    <%= link_to 'Back to friends', friends_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="footer footer-center p-4 bg-base-300 text-base-content absolute bottom-0 mt-14 flex justify-center">

     <% if cookies[:theme] == "light" %>
        <%= link_to root_path(theme: "dark"),class:"inline" do %>
          <svg class="swap-off fill-current h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"/></svg>
        <% end %>
      <% else %>
        <%= link_to root_path(theme: "light"),class:"inline" do %>
          <svg class="swap-on fill-current h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"/></svg>
        <% end %>
      <% end %>

      <p>
    Copyright © 2022 - All right reserved by ACME Industries Ltd
      </p>

</footer>

app/views/home/_header.html.erb
<div class="navbar bg-base-100 container mx-auto">
  <div class="navbar-start">
    <div class="dropdown">
      <label tabindex="0" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </label>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
        <li>
          <%= link_to "Friends", "/friends" %>
        </li>
      </ul>
    </div>
    <%= link_to 'Friend App', root_path, class:"btn btn-ghost normal-case text-xl" %>
  </div>

  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal p-0">
      <li>
        <%= link_to "Friends", "/friends" %>
      </li>
      <li>
        <%= link_to "About Us", about_path %>
      </li>
    </ul>
  </div>

  <div class="navbar-end">
    <div class="btn-group">
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn" %>
        <%= link_to "Profile", edit_user_registration_path, class:"btn" %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class:"btn" %>
        <%= link_to "Sign In", new_user_session_path, class:"btn" %>
      <% end%>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="flex justify-center flex-wrap">

<div class="card lg:card-side bg-base-100 shadow-xl max-h-[50vh] w-full">
  <figure class="w-1/2"><%= image_tag "organize.jpg", class:"w-full h-full max-w-[300px] object-cover" %></figure>
  <div class="card-body">
    <h2 class="card-title">Organisation</h2>
    <p>Click the button to listen on Spotiwhy app.</p>
    <div class="card-actions justify-end">
      <button class="btn btn-primary">Listen</button>
    </div>
  </div>
</div>

<div class="card lg:card-side bg-base-100 shadow-xl max-h-[50vh] mt-8 w-full">
  <div class="card-body">
    <h2 class="card-title">AI friends</h2>
    <p class="grow-0">Who needs real friends when you can have AI friends?</p>
    <b>Pros:</b>
    <ul>
      <li>Don't cancel plans</li>
    </ul>
    <b>Cons:</b>
    <ul class="grow">
      <li>Slight chance of world domination (<i>&lt; 20%</i>)</li>
    </ul>
    <div class="card-actions justify-start">
      <button class="btn btn-primary">Talk to us</button>
    </div>
  </div>
  <figure><%= image_tag "robot.jpg", class:"w-full h-full max-w-[300px] object-cover" %></figure>
</div>

</div>

app/views/home/index.html.erb
<div class="hero h-[50vh] rounded-xl" style="background-image: url(https://cdn.lorem.space/images/fashion/.cache/1000x800/felipe-galvan-AhfrA5VQNpM-unsplash.jpg);">
  <div class="hero-overlay bg-opacity-60 rounded-xl" ></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-md">
      <h1 class="mb-5 text-5xl font-bold">Hello there</h1>
      <p class="mb-5">You might have heard of "friends" or maybe already have some...</p>
      <p class="mb-5">We help you keep your friends organized, think of us as "Friends 2.0"</p>


      <% if user_signed_in? %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success shadow-lg mb-8">
  <div>
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
    <%= notice %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="icon" type="image/svg+xml" href="/favicon.svg"/>
  </head>

  <body class="min-h-screen relative pb-[100px]" data-theme="<%= cookies[:theme] %>">

    <%= render 'home/header' %>

    <main class="container mx-auto mt-14 px-5">

      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </main>

    <%= render 'home/footer' %>
  </body>
</html>